name: CD - Build and Push Image Docker


on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io # Github Container Registry
  IMAGE_NAME: landidaniel/integracao-ci-cd

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login Github Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::434352151503:role/OIDCGithubActionsRole
      
      - name: Validar identidade (AWS <> OIDC)
        run: |
          echo "Testando conexão com a AWS.."
          aws sts get-caller-identity

  deploy-production:
    needs: build-and-push
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://fiap.com.br

    env:
      API_ENV: "production"
      LOG_LEVEL: "WARNING"
      MODEL_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Atualizar imagem do deployment (k8s)
        run: |
          sed -i "s|image: nginx:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MODEL_TAG }}|g" k8s/deployment.yaml
          sed -i "s|API_ENV_PLACEHOLDER|${{ env.API_ENV }}|g" k8s/deployment.yaml

      - name: Deploy - Production
        run: |
          echo "O arquivo YAML mutado que será enviado para nuvem"
          cat k8s/deployment.yaml
          echo "Deploy executado com sucesso"