name: CD - Build and Push Image Docker


on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io # Github Container Registry
  IMAGE_NAME: landidaniel/Integracao-ci-cd

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login Github Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::434352151503:role/OIDCGithubActionsRole
      
      - name: Validar identidade (AWS <> OIDC)
        run: |
          echo "Testando conexão com a AWS.."
          aws sts get-caller-identity